name: mosdef
channels:
  - conda-forge
dependencies:
  - ele
  - mbuild
  - numpy=1.24.2
  - packmol>=18
  - gmso>=0.9.0
  - foyer
  - parmed>=3.4.3
  - python>=3.8
  - rdkit>=2021
  - scipy
  - networkx
  - treelib
  - importlib_resources
